add project for verification
kimdeun/Scooter_UI_Tests pull request #1
Opened 2022-08-07 08:59 UTC by kimdeun

2022-08-07 18:13 UTC, pavel-ulan requested changes
Начнем с того, что папка .idea не коммитится в репозиторий.
В остальном, вроде особых вопросов нет, кроме реализации теста на вопросы. его надо переделать. Глянь комменты пожалуйста.

2022-08-07 18:13 UTC, pavel-ulan commented on src/main/java/ru/yandex/scooter/Main.java
> +    }
а зачем тебе main класс в работе?

2022-08-07 18:13 UTC, pavel-ulan commented on src/main/java/ru/yandex/scooter/pageobject/HomePageScooter.java
> +
поработай с выравниванием, столько пустых строк быть не должно.
можно использовать хоткеи для автовыравнивания (ctrl+alt+L вроде).

2022-08-07 18:13 UTC, pavel-ulan commented on src/test/java/FrequentlyAskedQuestionsTests.java
> +           assertEquals(homePage.checkContentOfDropDownListNum8(), answer);
Эм, это очень плохая реализация теста. Начнем с того, что это просто странно использовать столько if/else конструкций. Плюс понимай, что каждое вложение, это кратное увеличение ресурсов на обработку (да, для таких тестов это несущественно, но если бы это были сложные вычисления....).
Ну и вишенкой на торте: по заданию "Важно написать отдельный тест на каждый вопрос.". И в целом, я согласен, что этот тест идеален для параметризации, но все же следует придерживаться условий тесткейса.

2022-08-09 14:35 UTC, kimdeun commented
Исправил замечания в [коммите](https://github.com/kimdeun/Sprint_4/pull/1/commits/799555b13fabdb08fed0480b63fd2ae03e94f4d0)

2022-08-11 12:07 UTC, pavel-ulan approved these changes
Оке

2022-08-28 13:28 UTC, merged